#!/usr/bin/env bash
set -euo pipefail

STORE="taguardian-fr.myshopify.com"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEME_DIR="$SCRIPT_DIR/taguardian-theme"

echo "=========================================="
echo "  Setup — Shopify Store taguardian.fr"
echo "=========================================="
echo ""

# ── Tâche 0 : vérification Shopify CLI ────────────────────────────────────────
echo "[ 1/3 ] Vérification de Shopify CLI..."
if ! command -v shopify &>/dev/null; then
  echo "ERREUR : Shopify CLI non trouvé."
  echo "Installez-le avec : brew tap shopify/shopify && brew install shopify-cli"
  exit 1
fi
echo "  → Shopify CLI $(shopify version) détecté."
echo ""

# ── Tâche 1 : push du thème ───────────────────────────────────────────────────
echo "[ 2/3 ] Push du thème vers $STORE..."
echo "  → Lancement de : shopify theme push --store $STORE"
echo ""
shopify theme push --path "$THEME_DIR" --store "$STORE"
echo ""
echo "  ✓ Thème pushé avec succès."
echo ""

# ── Tâche 2 : instructions manuelles ──────────────────────────────────────────
echo "[ 3/3 ] Étapes manuelles restantes"
echo "──────────────────────────────────────────"
echo ""
echo "  A) IMPORTER LES PRODUITS"
echo "     1. Ouvrez l'Admin Shopify : https://admin.shopify.com/store/taguardian-fr"
echo "     2. Allez dans Produits → Importer"
echo "     3. Sélectionnez le fichier : $SCRIPT_DIR/products.csv"
echo "     4. Cochez « Remplacer les produits existants »"
echo "     5. Cliquez sur « Importer »"
echo ""
echo "  B) CRÉER LES COLLECTIONS (condition : tag)"
echo "     Créez les 5 collections suivantes depuis :"
echo "     Admin → Contenu → Collections → Créer une collection"
echo ""
echo "     Collection              Condition (tag égal à)"
echo "     ─────────────────────   ──────────────────────"
echo "     Vêtements femme         vêtements-femme"
echo "     Vêtements homme         vêtements-homme"
echo "     Accessoires             accessoires"
echo "     Chaussures              chaussures"
echo "     Maison & Déco           maison-deco"
echo ""
echo "     Pour chaque collection :"
echo "       - Type : Automatique"
echo "       - Condition : Le tag du produit est égal à <valeur ci-dessus>"
echo ""
echo "     Vous pouvez aussi importer $SCRIPT_DIR/collections.csv via"
echo "     Admin → Contenu → Collections → Importer (si disponible sur votre plan)."
echo ""
echo "  C) CONFIGURER LE DOMAINE taguardian.fr"
echo "     1. Admin Shopify → Paramètres → Domaines → Ajouter un domaine existant"
echo "     2. Saisissez : taguardian.fr"
echo "     3. Shopify vous fournira 2 valeurs DNS à configurer :"
echo "        • Enregistrement A   : @ → IP Shopify (ex. 23.227.38.65)"
echo "        • Enregistrement CNAME: www → shops.myshopify.com"
echo "     4. Connectez-vous à votre espace OVH :"
echo "        https://www.ovh.com/manager/ → Domaines → taguardian.fr → Zone DNS"
echo "     5. Supprimez les enregistrements A et CNAME existants pour @ et www"
echo "     6. Ajoutez les nouvelles valeurs fournies par Shopify"
echo "     7. Retournez dans l'Admin Shopify et cliquez sur « Vérifier la connexion »"
echo "     Note : la propagation DNS peut prendre jusqu'à 48h."
echo ""
echo "=========================================="
echo "  Setup terminé !"
echo "=========================================="
